# Generated by Django 5.1.7 on 2025-04-17 16:53

from django.db import migrations
from django.utils.text import slugify


def generate_slugs(apps, schema_editor):
    Post = apps.get_model('home', 'Post')
    for post in Post.objects.all():
        if not post.slug:
            post.slug = slugify(post.title)
            post.save()


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(generate_slugs),
    ]
