# Generated by Django 5.1.7 on 2025-04-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_articlecategory_post_is_published_post_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='post',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
